# Generated by Django 4.2.4 on 2023-08-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=15)),
                ('dependants', models.IntegerField()),
                ('applicantincome', models.IntegerField()),
                ('loanamt', models.IntegerField()),
                ('credithistory', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('married', models.CharField(max_length=15)),
                ('graduateeducation', models.CharField(max_length=15)),
                ('selfemployed', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=15)),
            ],
        ),
    ]
