# Generated by Django 4.2.4 on 2023-08-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0002_alter_approval_area_alter_approval_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='coapplicantincome',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='approval',
            name='loanamt_term',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
