# Generated by Django 4.2.4 on 2023-08-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0003_approval_coapplicantincome_approval_loanamt_term'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='applicantincome',
            new_name='ApplicantIncome',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='coapplicantincome',
            new_name='CoapplicantIncome',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='credithistory',
            new_name='Credit_History',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='dependants',
            new_name='Dependents',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='graduateeducation',
            new_name='Education',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='loanamt',
            new_name='LoanAmount',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='loanamt_term',
            new_name='Loan_Amount_Term',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='married',
            new_name='Married',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='area',
            new_name='Property_Area',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='selfemployed',
            new_name='Self_Employed',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='lastname',
        ),
    ]
